### ISSUE TITLE
Multiple holes

### ISSUE THREAD

**Issue by Shatur** [frewsxcv/earcutr#2]
Is it possible to cut multiple holes? If I understand correctly, [C++ version](https://github.com/mapbox/earcut.hpp) accepts multiple holes.

**Comment by frewsxcv** [comment]
Yep. See https://github.com/frewsxcv/bevy-earcutr/blob/master/src/lib.rs#L12 for an example

You specify an index in the vertices vector for each interior hole you have

**Comment by Shatur** [comment]
Oh, right, I somehow misinterpreted the input I need to pass. Thank you!

**Comment by Shatur** [comment]
> You specify an index in the vertices vector for each interior hole you have

@frewsxcv Or maybe not... Are you referring to holes as points that will be cut? But is it possible to cut two actual holes like this?
```
__________
|         |
|  /|  /| |
| /_| /_| |
|_________|
```
In C++ version we have multiple vectors: first one for the exterior and all next will be for the inner holes. But in this library I see only two vectors one for all points and another one for all indicies that will be cut. I don't understand how to separate these indices in figures I want to cut.

**Comment by frewsxcv** [comment]
https://github.com/frewsxcv/earcutr/blob/52f58d8c3885e4040386c00af98c1787b395ec18/src/tests.rs#L596-L609

Indices represent the start index of holes

**Comment by Shatur** [comment]
Oh, now I get, thank you a lot!
